### ISSUE TITLE
Restrict PostgreSQL access, at least with authentication

### ISSUE THREAD

**Issue by ymartin59** [jfrog/JFrog-Cloud-Installers#35]
I wonder about the relevance of line `host    all             all             0.0.0.0/0               trust`
in https://github.com/jfrog/JFrog-Cloud-Installers/blob/master/Ansible/ansible_collections/jfrog/installers/roles/postgres/templates/pg_hba.conf.j2#L7

Are target clouds infrastructure already so secure that there is no risk any user may connect from anywhere without any authentication method? (ok offender may have to guess a valid postgresql username)

**Comment by jefferyfry** [comment]
We have made pg_hba.conf configurable so that you can change/add client authentication configuration in the latest v1.1.0.

https://github.com/jfrog/JFrog-Cloud-Installers/blob/master/Ansible/ansible_collections/jfrog/installers/roles/postgres/templates/pg_hba.conf.j2#L7

https://github.com/jfrog/JFrog-Cloud-Installers/blob/master/Ansible/ansible_collections/jfrog/installers/roles/postgres/defaults/main.yml#L86
